oops, we can't make Token copyable because it has owned Strings!
src/token.rs:14:17: 14:21 error: the trait `Copy` may not be implemented for this type; variant `DecimalInt` does not implement `Copy` [E0205]
src/token.rs:14 #[derive(Debug, Copy, PartialEq)]
                                ^~~~
note: in expansion of #[derive_Copy]
src/token.rs:14:17: 14:21 note: expansion site
error: aborting due to previous error