token buffer doesn't work because Token isn't copyable
src/lexer.rs:97:21: 97:45 error: cannot move out of type `[token::Token; 4]`, a non-copy fixed-size array
src/lexer.rs:97         let token = self.tokens[self.cursor];
                                    ^~~~~~~~~~~~~~~~~~~~~~~~
src/lexer.rs:97:13: 97:18 note: attempting to move value to here
src/lexer.rs:97         let token = self.tokens[self.cursor];
                            ^~~~~
src/lexer.rs:97:18: 97:18 help: to prevent the move, use `ref token` or `ref mut token` to capture value by reference
error: aborting due to previous error